### ISSUE TITLE
fryse command not found

### ISSUE THREAD

**Issue by easybeau** [fryse/fryse#13]
Hi,

Thanks for this static site generator.

I used the command `mix escript.install hex fryse` to install fryse.

At the end, I got the following message:
`* creating /home/xxx/.mix/escripts/fryse
warning: you must append "/home/xxx/.mix/escripts" to your PATH if you want to invoke escripts by name`

Then I tried to create my blog using command `fryse`. Command not found

I put the variable PATH in `.bashrc` -> `export PATH="$PATH:/home/xxx/.mix/escripts"`

What's wrong ?
Best regards

**Comment by PhillippOhlandt** [comment]
Hey,

that looks right to me. My guess here is that you are still in the same console session which does not know about the new `PATH`. Either reopen the console or try `source ~/.bashrc` to reload the variable.

**Comment by easybeau** [comment]
Yesss, it works! I forgot to reload the variable. Thanks
