### ISSUE TITLE
Fonts don't appear online

### ISSUE THREAD

**Issue by easybeau** [fryse/fryse#14]
Hi again,

I put a test website online and the awesome fonts don't appear online but only locally.
Locally 
![menu](https://user-images.githubusercontent.com/7128391/88043980-2eb93a00-cb4e-11ea-95bd-c7c96b0c9a7d.png)

Online
![menu_online](https://user-images.githubusercontent.com/7128391/88044143-3d9fec80-cb4e-11ea-9e86-7dd78cabf897.png)

I added the lines to config.yml :

>   - from: fonts
    to: assets/fonts

Could you help me. Thank you
Best,

**Comment by PhillippOhlandt** [comment]
Hey,

the font files should be copied over (make sure they are in the generated folder). My guess is that you have not referenced them in your CSS.

This should do the trick:
https://www.w3schools.com/cssref/css3_pr_font-face_rule.asp

**Comment by easybeau** [comment]
I have a fonts.css file in which the fonts appear like this but they are not referenced on default.css (with body, etc). Both css files are referenced in layouts.

`@font-face
{
	font-family: 'FontAwesome';
	src: url('../fonts/fontawesome-webfont.eot?v=3.0.1');
	src: url('../fonts/fontawesome-webfont.eot?#iefix&v=3.0.1') format('embedded-opentype'),
	     url('../fonts/fontawesome-webfont.woff?v=3.0.1') format('woff'),
	     url('../fonts/fontawesome-webfont.ttf?v=3.0.1') format('truetype'),
	     url('../fonts/fontawesome-webfont.svg#FontAwesome') format('svg');
	font-weight: normal;
	font-style: normal;
}

@font-face
{
	font-family: 'Font-Awesome-Social';
	src: url('../fonts/fontawesome-social-webfont.eot');
	src: url('../fonts/fontawesome-social-webfont.eot?#iefix') format('embedded-opentype'),
	     url('../fonts/fontawesome-social-webfont.woff') format('woff'),
		 url('../fonts/fontawesome-social-webfont.ttf') format('truetype'),
		 url('../fonts/fontawesome-social-webfont.svg#Font-Awesome-More') format('svg');
	font-weight: normal;
	font-style: normal;
}`

**Comment by easybeau** [comment]
Sorry, some of the fonts are missing in fonts directory. I guess they are not free !

Thanks
