### ISSUE TITLE
Correct syntact src attribute in html.eex

### ISSUE THREAD

**Issue by easybeau** [fryse/fryse#15]
Hey,

I have a few js files that I want to include in my website.

I guess it's wrong to write it this way in html.eex

`<script src="../js/portfolio.js"></script>`

What's the correct syntax for linking with src attribute?

Thanks

**Comment by PhillippOhlandt** [comment]
I recommend to use the `asset` helper function in the templates.
You can find an example here in the starter project:
https://github.com/fryse/starter-project/blob/master/themes/default/layouts/default.html.eex#L14

So, in your case, it would be:
`<script src="<%= asset(@page, 'js/portfolio.js') %>"></script>`

**Comment by easybeau** [comment]
Thank you very much for your answer !

Best,
